version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - my_data:/var/www/html/my-data

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: always
    volumes:
      - my_data:/var/www/html/my-data

volumes:
  my_data: