version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - content_data:/var/www/html/content

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: always
    volumes:
      - content_data:/var/www/html/content

volumes:
  content_data: