<?php
/**
 * World Countries Data for Sambazen.net
 */

$countries = [
    ['name' => 'India', 'population' => 1428627663, 'capital' => 'New Delhi', 'region' => 'Asia'],
    ['name' => 'China', 'population' => 1425671352, 'capital' => 'Beijing', 'region' => 'Asia'],
    ['name' => 'United States', 'population' => 339996563, 'capital' => 'Washington, D.C.', 'region' => 'Americas'],
    ['name' => 'Indonesia', 'population' => 277534122, 'capital' => 'Jakarta', 'region' => 'Asia'],
    ['name' => 'Pakistan', 'population' => 240485658, 'capital' => 'Islamabad', 'region' => 'Asia'],
    ['name' => 'Nigeria', 'population' => 223804632, 'capital' => 'Abuja', 'region' => 'Africa'],
    ['name' => 'Brazil', 'population' => 216422446, 'capital' => 'Brasília', 'region' => 'Americas'],
    ['name' => 'Bangladesh', 'population' => 172954319, 'capital' => 'Dhaka', 'region' => 'Asia'],
    ['name' => 'Russia', 'population' => 144444359, 'capital' => 'Moscow', 'region' => 'Europe/Asia'],
    ['name' => 'Mexico', 'population' => 128455567, 'capital' => 'Mexico City', 'region' => 'Americas'],
    ['name' => 'Ethiopia', 'population' => 126527060, 'capital' => 'Addis Ababa', 'region' => 'Africa'],
    ['name' => 'Japan', 'population' => 123294513, 'capital' => 'Tokyo', 'region' => 'Asia'],
    ['name' => 'Philippines', 'population' => 117337368, 'capital' => 'Manila', 'region' => 'Asia'],
    ['name' => 'Egypt', 'population' => 112716598, 'capital' => 'Cairo', 'region' => 'Africa/Asia'],
    ['name' => 'DR Congo', 'population' => 102262808, 'capital' => 'Kinshasa', 'region' => 'Africa'],
    ['name' => 'Vietnam', 'population' => 98858950, 'capital' => 'Hanoi', 'region' => 'Asia'],
    ['name' => 'Iran', 'population' => 89172767, 'capital' => 'Tehran', 'region' => 'Asia'],
    ['name' => 'Turkey', 'population' => 85816199, 'capital' => 'Ankara', 'region' => 'Europe/Asia'],
    ['name' => 'Germany', 'population' => 83294633, 'capital' => 'Berlin', 'region' => 'Europe'],
    ['name' => 'Thailand', 'population' => 71801279, 'capital' => 'Bangkok', 'region' => 'Asia'],
    ['name' => 'United Kingdom', 'population' => 67736802, 'capital' => 'London', 'region' => 'Europe'],
    ['name' => 'Tanzania', 'population' => 67438106, 'capital' => 'Dodoma', 'region' => 'Africa'],
    ['name' => 'France', 'population' => 64756584, 'capital' => 'Paris', 'region' => 'Europe'],
    ['name' => 'South Africa', 'population' => 60414495, 'capital' => 'Pretoria', 'region' => 'Africa'],
    ['name' => 'Italy', 'population' => 58870762, 'capital' => 'Rome', 'region' => 'Europe'],
    ['name' => 'Kenya', 'population' => 55100586, 'capital' => 'Nairobi', 'region' => 'Africa'],
    ['name' => 'Myanmar', 'population' => 54577997, 'capital' => 'Naypyidaw', 'region' => 'Asia'],
    ['name' => 'Colombia', 'population' => 52085168, 'capital' => 'Bogota', 'region' => 'Americas'],
    ['name' => 'South Korea', 'population' => 51784059, 'capital' => 'Seoul', 'region' => 'Asia'],
    ['name' => 'Uganda', 'population' => 48582334, 'capital' => 'Kampala', 'region' => 'Africa'],
    ['name' => 'Sudan', 'population' => 48109006, 'capital' => 'Khartoum', 'region' => 'Africa'],
    ['name' => 'Spain', 'population' => 47519628, 'capital' => 'Madrid', 'region' => 'Europe'],
    ['name' => 'Argentina', 'population' => 45773884, 'capital' => 'Buenos Aires', 'region' => 'Americas'],
    ['name' => 'Algeria', 'population' => 45606480, 'capital' => 'Algiers', 'region' => 'Africa'],
    ['name' => 'Iraq', 'population' => 45505911, 'capital' => 'Baghdad', 'region' => 'Asia'],
    ['name' => 'Afghanistan', 'population' => 42239854, 'capital' => 'Kabul', 'region' => 'Asia'],
    ['name' => 'Poland', 'population' => 41026067, 'capital' => 'Warsaw', 'region' => 'Europe'],
    ['name' => 'Canada', 'population' => 38781291, 'capital' => 'Ottawa', 'region' => 'Americas'],
    ['name' => 'Morocco', 'population' => 37840044, 'capital' => 'Rabat', 'region' => 'Africa'],
    ['name' => 'Saudi Arabia', 'population' => 36947025, 'capital' => 'Riyadh', 'region' => 'Asia'],
    ['name' => 'Ukraine', 'population' => 36744634, 'capital' => 'Kyiv', 'region' => 'Europe'],
    ['name' => 'Angola', 'population' => 36684202, 'capital' => 'Luanda', 'region' => 'Africa'],
    ['name' => 'Uzbekistan', 'population' => 35163944, 'capital' => 'Tashkent', 'region' => 'Asia'],
    ['name' => 'Yemen', 'population' => 34449825, 'capital' => 'Sanaa', 'region' => 'Asia'],
    ['name' => 'Peru', 'population' => 34352719, 'capital' => 'Lima', 'region' => 'Americas'],
    ['name' => 'Malaysia', 'population' => 34308525, 'capital' => 'Kuala Lumpur', 'region' => 'Asia'],
    ['name' => 'Ghana', 'population' => 34121985, 'capital' => 'Accra', 'region' => 'Africa'],
    ['name' => 'Mozambique', 'population' => 33897354, 'capital' => 'Maputo', 'region' => 'Africa'],
    ['name' => 'Nepal', 'population' => 30896590, 'capital' => 'Kathmandu', 'region' => 'Asia'],
    ['name' => 'Madagascar', 'population' => 30325732, 'capital' => 'Antananarivo', 'region' => 'Africa'],
    ['name' => 'Australia', 'population' => 26439111, 'capital' => 'Canberra', 'region' => 'Oceania'],
    ['name' => 'North Korea', 'population' => 26160821, 'capital' => 'Pyongyang', 'region' => 'Asia'],
    ['name' => 'Cameroon', 'population' => 28647293, 'capital' => 'Yaoundé', 'region' => 'Africa'],
    ['name' => 'Niger', 'population' => 27202843, 'capital' => 'Niamey', 'region' => 'Africa'],
    ['name' => 'Taiwan', 'population' => 23923276, 'capital' => 'Taipei', 'region' => 'Asia'],
    ['name' => 'Mali', 'population' => 23293698, 'capital' => 'Bamako', 'region' => 'Africa'],
    ['name' => 'Burkina Faso', 'population' => 23251485, 'capital' => 'Ouagadougou', 'region' => 'Africa'],
    ['name' => 'Sri Lanka', 'population' => 21893579, 'capital' => 'Colombo', 'region' => 'Asia'],
    ['name' => 'Malawi', 'population' => 20931751, 'capital' => 'Lilongwe', 'region' => 'Africa'],
    ['name' => 'Zambia', 'population' => 20569737, 'capital' => 'Lusaka', 'region' => 'Africa'],
    ['name' => 'Romania', 'population' => 19892812, 'capital' => 'Bucharest', 'region' => 'Europe'],
    ['name' => 'Chile', 'population' => 19629590, 'capital' => 'Santiago', 'region' => 'Americas'],
    ['name' => 'Kazakhstan', 'population' => 19397998, 'capital' => 'Astana', 'region' => 'Asia'],
    ['name' => 'Ecuador', 'population' => 18190484, 'capital' => 'Quito', 'region' => 'Americas'],
    ['name' => 'Guatemala', 'population' => 18092026, 'capital' => 'Guatemala City', 'region' => 'Americas'],
    ['name' => 'Chad', 'population' => 17723315, 'capital' => "N'Djamena", 'region' => 'Africa'],
    ['name' => 'Somalia', 'population' => 17597511, 'capital' => 'Mogadishu', 'region' => 'Africa'],
    ['name' => 'Netherlands', 'population' => 17564014, 'capital' => 'Amsterdam', 'region' => 'Europe'],
    ['name' => 'Senegal', 'population' => 17316449, 'capital' => 'Dakar', 'region' => 'Africa'],
    ['name' => 'Cambodia', 'population' => 16767842, 'capital' => 'Phnom Penh', 'region' => 'Asia'],
    ['name' => 'Zimbabwe', 'population' => 16320537, 'capital' => 'Harare', 'region' => 'Africa'],
    ['name' => 'Guinea', 'population' => 13859341, 'capital' => 'Conakry', 'region' => 'Africa'],
    ['name' => 'Rwanda', 'population' => 13776698, 'capital' => 'Kigali', 'region' => 'Africa'],
    ['name' => 'Benin', 'population' => 13352864, 'capital' => 'Porto-Novo', 'region' => 'Africa'],
    ['name' => 'Burundi', 'population' => 13238559, 'capital' => 'Bujumbura', 'region' => 'Africa'],
    ['name' => 'Tunisia', 'population' => 12356117, 'capital' => 'Tunis', 'region' => 'Africa'],
    ['name' => 'Bolivia', 'population' => 12224110, 'capital' => 'Sucre', 'region' => 'Americas'],
    ['name' => 'Belgium', 'population' => 11655930, 'capital' => 'Brussels', 'region' => 'Europe'],
    ['name' => 'Haiti', 'population' => 11584996, 'capital' => 'Port-au-Prince', 'region' => 'Americas'],
    ['name' => 'Jordan', 'population' => 11285869, 'capital' => 'Amman', 'region' => 'Asia'],
    ['name' => 'Cuba', 'population' => 11212191, 'capital' => 'Havana', 'region' => 'Americas'],
    ['name' => 'Dominican Republic', 'population' => 11228821, 'capital' => 'Santo Domingo', 'region' => 'Americas'],
    ['name' => 'Czech Republic', 'population' => 10493986, 'capital' => 'Prague', 'region' => 'Europe'],
    ['name' => 'Sweden', 'population' => 10549347, 'capital' => 'Stockholm', 'region' => 'Europe'],
    ['name' => 'Greece', 'population' => 10384971, 'capital' => 'Athens', 'region' => 'Europe'],
    ['name' => 'Portugal', 'population' => 10143816, 'capital' => 'Lisbon', 'region' => 'Europe'],
    ['name' => 'Azerbaijan', 'population' => 10412651, 'capital' => 'Baku', 'region' => 'Asia'],
    ['name' => 'Hungary', 'population' => 9643048, 'capital' => 'Budapest', 'region' => 'Europe'],
    ['name' => 'Tajikistan', 'population' => 9952787, 'capital' => 'Dushanbe', 'region' => 'Asia'],
    ['name' => 'United Arab Emirates', 'population' => 9441129, 'capital' => 'Abu Dhabi', 'region' => 'Asia'],
    ['name' => 'Israel', 'population' => 9174520, 'capital' => 'Jerusalem', 'region' => 'Asia'],
    ['name' => 'Austria', 'population' => 8939617, 'capital' => 'Vienna', 'region' => 'Europe'],
    ['name' => 'Switzerland', 'population' => 8740472, 'capital' => 'Bern', 'region' => 'Europe'],
    ['name' => 'Togo', 'population' => 8848696, 'capital' => 'Lomé', 'region' => 'Africa'],
    ['name' => 'Sierra Leone', 'population' => 8605718, 'capital' => 'Freetown', 'region' => 'Africa'],
    ['name' => 'Laos', 'population' => 7529475, 'capital' => 'Vientiane', 'region' => 'Asia'],
    ['name' => 'Hong Kong', 'population' => 7488865, 'capital' => 'Hong Kong', 'region' => 'Asia'],
    ['name' => 'Serbia', 'population' => 7149077, 'capital' => 'Belgrade', 'region' => 'Europe'],
    ['name' => 'Libya', 'population' => 6812341, 'capital' => 'Tripoli', 'region' => 'Africa'],
];

// Sort by population descending
usort($countries, function($a, $b) {
    return $b['population'] - $a['population'];
});
